#!/usr/bin/env bash

FILES=$(git diff --cached --name-only --diff-filter=ACM \
  | grep -E '^(src|include)/.*\.(cpp|hpp|c|h)$')
  
#file naming
echo "Checking file naming conventions..."

BAD_FILES=0
for file in $FILES; do
  filename=$(basename "$file")

  # snake_case only
  if [[ ! "$filename" =~ ^[a-z0-9_]+\.(cpp|hpp|c|h)$ ]]; then
    echo "   Invalid file name: $file"
    echo "   Use snake_case (example: phone_parser.cpp)"
    BAD_FILES=1
  fi
done

if [ "$BAD_FILES" -ne 0 ]; then
  echo "Commit blocked due to file naming violations."
  exit 1
fi


#format 
BAD_FORMAT=0
echo "Running clang-format..."
for file in $FILES; do
  if ! clang-format --dry-run --Werror "$file" ; then
    echo "   $file needs to be formatted!"
    BAD_FORMAT=1
  fi
done

if [ "$BAD_FORMAT" -ne 0 ]; then
  echo "Commit blocked due to formatting violations. Use make format to auto format or fix manually"
  exit 1
fi

exit 0