name: Run clang-format

on:
  push:
  pull_request:

jobs:
  clang_format:
    name: Clang Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          FILES=$(find ../src ../include -type f | grep -E '\.(cpp|hpp|c|h)$')
          for f in $FILES; do
            clang-format --dry-run --Werror "$f"
          done

